/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as RakesRouteImport } from './routes/rakes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CentreCentreIdSectionRouteImport } from './routes/centre.$centreId.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const RakesRoute = RakesRouteImport.update({
  id: '/rakes',
  path: '/rakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreCentreIdSectionRoute = CentreCentreIdSectionRouteImport.update({
  id: '/centre/$centreId/$section',
  path: '/centre/$centreId/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centres': typeof CentresRoute
  '/rakes': typeof RakesRoute
  '/reports': typeof ReportsRoute
  '/centre/$centreId/$section': typeof CentreCentreIdSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centres': typeof CentresRoute
  '/rakes': typeof RakesRoute
  '/reports': typeof ReportsRoute
  '/centre/$centreId/$section': typeof CentreCentreIdSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centres': typeof CentresRoute
  '/rakes': typeof RakesRoute
  '/reports': typeof ReportsRoute
  '/centre/$centreId/$section': typeof CentreCentreIdSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/centres' | '/rakes' | '/reports' | '/centre/$centreId/$section'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/centres' | '/rakes' | '/reports' | '/centre/$centreId/$section'
  id:
    | '__root__'
    | '/'
    | '/centres'
    | '/rakes'
    | '/reports'
    | '/centre/$centreId/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentresRoute: typeof CentresRoute
  RakesRoute: typeof RakesRoute
  ReportsRoute: typeof ReportsRoute
  CentreCentreIdSectionRoute: typeof CentreCentreIdSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rakes': {
      id: '/rakes'
      path: '/rakes'
      fullPath: '/rakes'
      preLoaderRoute: typeof RakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre/$centreId/$section': {
      id: '/centre/$centreId/$section'
      path: '/centre/$centreId/$section'
      fullPath: '/centre/$centreId/$section'
      preLoaderRoute: typeof CentreCentreIdSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentresRoute: CentresRoute,
  RakesRoute: RakesRoute,
  ReportsRoute: ReportsRoute,
  CentreCentreIdSectionRoute: CentreCentreIdSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
